services:
  - type: web
    name: vuk-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run install-frontend && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
